// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5nrDg794mMsIecRIvKa-MgC54Y-w5QPI',
    appId: '1:862347042390:web:05e02c4c8ed299835725f7',
    messagingSenderId: '862347042390',
    projectId: 'hi-bank-test',
    authDomain: 'hi-bank-test.firebaseapp.com',
    storageBucket: 'hi-bank-test.appspot.com',
    measurementId: 'G-L38QMTBRVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCop-0jAqHQTgp8TDYysKCK57JluEjWDDQ',
    appId: '1:862347042390:android:5850da90711207895725f7',
    messagingSenderId: '862347042390',
    projectId: 'hi-bank-test',
    storageBucket: 'hi-bank-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6gEimMl4jOrHjYqdSZmDa1aDXK2Cgg2A',
    appId: '1:862347042390:ios:11f6511f1449391a5725f7',
    messagingSenderId: '862347042390',
    projectId: 'hi-bank-test',
    storageBucket: 'hi-bank-test.appspot.com',
    iosBundleId: 'com.example.hiBankTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6gEimMl4jOrHjYqdSZmDa1aDXK2Cgg2A',
    appId: '1:862347042390:ios:11f6511f1449391a5725f7',
    messagingSenderId: '862347042390',
    projectId: 'hi-bank-test',
    storageBucket: 'hi-bank-test.appspot.com',
    iosBundleId: 'com.example.hiBankTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5nrDg794mMsIecRIvKa-MgC54Y-w5QPI',
    appId: '1:862347042390:web:735b87251283cb645725f7',
    messagingSenderId: '862347042390',
    projectId: 'hi-bank-test',
    authDomain: 'hi-bank-test.firebaseapp.com',
    storageBucket: 'hi-bank-test.appspot.com',
    measurementId: 'G-YGBQSZSGH0',
  );
}
